### ISSUE TITLE
[BUG] Modernization Scanner Does Not Identify Workflows associated with List Content Types

### ISSUE THREAD

**Issue by rpwise** [pnp/sp-dev-modernization#541]
Thank you for reporting a bug. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. Thanks!

#### Problem Area

[ ] Page Transformation: Error during the use of page transformation from PnP PowerShell
[ ] Page Transformation: Error during the use of page transformation from .Net
[ ] Page Transformation: Page is not looking correct after transformation
[ ] Modernization Scanner: something went wrong...

None of the above apply.  The scanner does not throw an error, it is missing information.

#### Expected or Desired Behavior

I expect that the modernization scanner would pick up workflows associated with List Content Types.

#### Observed Behavior

The Modernization Scanner does not pick up workflows associated with List Content Types

#### Steps to Reproduce

Ensure there is a workflow associated with a list content type.  Run the Modernization Scanner to get the full workflow details.  The workflow will not be listed in the CSV.

**Comment by jansenbe** [comment]
Thanks @rpwise for logging this. In my testing I see workflows on content types, so seems as this is not that all content type workflows are missed. Do you have more details about the workflows that are not shown? If I can repro this from my side then I hope I can get it fixed and release a new version in the coming days.

**Comment by rpwise** [comment]
Thanks @jansenbe for the quick response.  Yes, the modernization scanner picks up workflows when they are applied to a site content type, but not a list content type.

Here are the details of my specific issue:
Create a list, turn on content type management.
Add the 'Event' content type from the existing site content types.  I don't believe which one matters, but this is the specific one I'm seeing.
Navigate to the list settings page, click on the 'Event' content type, then click 'Workflow settings'
Create or apply a workflow to this 'Event' list content type.  My specific one was a Three State workflow.
Run the modernization tool to get the workflow details.  This workflow will not show in the CSV.

I just worked with Microsoft and they confirmed that they were able to reproduce the issue on their end and they requested I submit this as a bug in GitHub.

**Comment by NicholasBlanchette** [comment]
We are also experiencing this issue with the scan of our tenant, however the workflows are showing up in the CSV but with all values empty including for some workflows which are effectively in use.

**Comment by jansenbe** [comment]
@NicholasBlanchette : that seems to be something different. What do you mean with "all values empty"? When a workflow is an OOB one we're not doing the analysis of the workflow actions itself. Also ensure you're running the latest version and that you run the "WorkflowWithDetails" mode. The basic workflow scan mode will not analyze the workflows, it will just list them

**Comment by jansenbe** [comment]
Hi @rpwise : I've just released version 2.18 that should fix the detection of workflows on list content types. Please give it a try and let us know if it works for you.

**Comment by rpwise** [comment]
@jansenbe Thank you for the update!  Let me download the latest version and give it a try!

**Comment by rpwise** [comment]
I can confirm that the three state workflow is now being picked up by the 2.18.0.0 version of the modernization scanner.  Thank you so much for the quick turnaround!

**Comment by jansenbe** [comment]
Thanks for the quick feedback @rpwise . I'll close this issue then

**Comment by samGakhar** [comment]
The latest version of the SP modernization scanner tool 2.18 is still not returning the SPD WFs having manual start triggers. Kindly suggest!
